### PR TITLE
pretty storage path & github actions

### PR DESCRIPTION
**Pull request by egeneralov**
Hello!
I suggesting use Github Actions for releases and human-readable names of PV, like `${BASEDIR}/${NAMESPACE}/${PVC-NAME}`.

### CODE REVIEW

**Comment by runningman84** [comment]
Would you mind adding a pre command (should be called before doing the mkdir)? This would allow us to use btrfs subolumes...

**Comment by egeneralov** [comment]
@runningman84
You mean `btrfs subvolume create ${PATH}`? I think, it's possible, and can be added as additional feature. Will do this at week.

**Comment by runningman84** [comment]
yes that would be great

**Comment by yasker** [comment]
@egeneralov Thanks for the PR!

1. I haven't used GitHub Action yet but this looks great. However, previously we can build and run validation using `make` command locally (e.g. `go fmt`, `go lint`). I would love to still have that ability to verify the build locally before pushing to the repo.
2. Use `${NAMESPACE}/${PVC-NAME}` might be a bit confusing since PV can be reused by a different PVC (though we've set `reclaimPolicy` to `Delete` by default). Also, the deletion part will break the backward compatibility since the naming pattern changed. I am a bit hesitant to accept this change due to those reasons.

**Comment by runningman84** [comment]
@yasker what would you think about my idea with a pre command (for creation) and maybe a post command (for deletion) in order to support btrfs subvolumes?

**Comment by yasker** [comment]
@runningman84 Yeah, we can do that. It can be done by adding more options in [our configuration](https://github.com/rancher/local-path-provisioner#configuration). We would need a bit design on this, e.g. do we want to have it configured globally or per node?

**Comment by runningman84** [comment]
I would like to have it here:
```
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/opt/local-path-provisioner"]
                        "create_cmd":"btrfs subvolume create ${PATH}",
                        "delete_cmd":"btrfs subvolume delete ${PATH}"
                },
                {
                        "node":"yasker-lp-dev1",
                        "paths":["/opt/local-path-provisioner", "/data1"]
                        "create_cmd":"lvm create blabla ${PATH}",
                        "delete_cmd":"lvm delete blabla ${PATH}",
                        "reszie_cmd":"lvm resize"
                },
                {
                        "node":"yasker-lp-dev3",
                        "paths":[]
                        "create_cmd":null,
                        "delete_cmd":null
                }
```
It would be greate to have examples for btrfs and lvm which are most commonly used... with variables for PVC name, storage size and so on we could also ensure that no single volume would max out a single node.

**Comment by yasker** [comment]
@runningman84 Those look good in general. Can you file a feature request? Don't want to hijack the thread of PR.

**Comment by runningman84** [comment]
done https://github.com/rancher/local-path-provisioner/issues/67

**Comment by bk201** [comment]
@egeneralov  Hi, are you still able to work on this PR?
I would suggest rebasing and focus on only GitHub actions.
- For the pretty storage path part, the code was already changed, and changing it again might cause issues after upgrading (deleting a non-exist path).
- Do not removing the scripts folder to be consistent with other Rancher projects.

**Comment by innobead** [comment]
Closing the PR, it seems pending for a while.

@egeneralov feel free to contribute back.

**Pull request closed without merging**
