### PR TITLE
Fixing log error flag.Parse

### PR DESCRIPTION
**Pull request by allupaku**
Fixing Issue number #53

### CODE REVIEW

**Comment by yasker** [comment]
Hi @allupaku 

Have you tested the PR yet?

**Comment by allupaku** [comment]
Yes , I have tested this with our cluster.

**Comment by yasker** [comment]
Weird, it crashes immediately on my setup:

```
$ kubectl -n local-path-storage logs -f local-path-provisioner-5945d4655b-lnjjk
flag provided but not defined: -debug
Usage of local-path-provisioner:
  -alsologtostderr
    	log to standard error as well as files
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```

**Review by ShubhamInfoblox — APPROVED** [review]
It looks like an issue with the glog controller, it shows the error if `flag.Parse` is not called. 
This should fix this, can we merge this ?

**Comment by innobead** [comment]
Closing, due to #53 already an invalid issue.

**Pull request closed without merging**
