### PR TITLE
Fix helm chart

### PR DESCRIPTION
**Pull request by rxbn**
Fix the deployment template to use the configMap name provided by helm values.

### CODE REVIEW

**Comment by yasker** [comment]
@rxbn LGTM. You can remove the second commit since there are multiple places need version change. I will update them all when releasing.

**Comment by rxbn** [comment]
> @rxbn LGTM. You can remove the second commit since there are multiple places need version change. I will update them all when releasing.

Done :)

**Comment by yasker** [comment]
@rxbn Can you use `git rebase -i` and `git push --force` to remove the last two commits?

**Comment by rxbn** [comment]
> @rxbn Can you use `git rebase -i` and `git push --force` to remove the last two commits?

Done!

**Comment by yasker** [comment]
Merged, thanks!

**Pull request merged**
