### PR TITLE
Provide helper Pod params as env vars.

### LINKED ISSUE #175: Allow the helper pod to read params from env vars
Currently the helper pod receives its parameters as CLI options which requires a helper Pod script to parse them first as in [here](https://github.com/rancher/local-path-provisioner/blob/01eaa8c41a31796581b707a00418eaae7369d3aa/examples/quota/setup#L3). This result in redundant code and older scripts may not be compatible with newer local-path-provisioner versions anymore when they fail on unknown options as scripts often do.

Both of these problems can be avoided when parameters are provided to the helper Pod as env vars.

### PR DESCRIPTION
**Pull request by mgoltzsche**
For backward compatibility the CLI options are still provided.

Closes #175
Split from PR #166

### CODE REVIEW

**Comment by mgoltzsche** [comment]
@derekbit this PR is also ready for review - I just rebased it.

**Comment by derekbit** [comment]
@mgoltzsche 
Could you elaborate more the purpose of moving the the variables (absolutePath, sizeInBytes and volMode) to env variables? This will be helpful for understanding the series of the PRs clearly.

**Comment by mgoltzsche** [comment]
It reduces the amount of redundant code needed to configure a helper pod.

**Review by derekbit — APPROVED** [review]
LGTM

**Pull request merged**
