### PR TITLE
Helm: Add the support of multiple storageclass configurations

### LINKED ISSUE #316: Helm: Allow to configure several storageclass
With the release of #306, it's now possible to use different storageclass to route the data to different directories. It's very useful :medal_sports:  but it's not yet possible to use in the helm chart.

WDYT to update it to support this kind of configuration:
```
## For creating the StorageClass automatically:
storageClasses:
  create: true

  ## Set a provisioner name. If unset, a name will be generated.
  # provisionerName: rancher.io/local-path

  classes:
    # The default storageclass with random path selection
    # For retro-compatibility with version < 0..0.24
    local-path:
      ## Set StorageClass as the default StorageClass
      ## Ignored if storageClass.create is false
      defaultClass: false
      ## ReclaimPolicy field of the class, which can be either Delete or Retain
      reclaimPolicy: Delete

      ## The path where to store the volumes
      ## Must exist in nodePathMap, if not specified, the path would be chosen
      ## randomly when provisioning.
      # nodePath: /my/path
```

### PR DESCRIPTION
**Pull request by vsellier**
Resolves #316

### CODE REVIEW

**Comment by JuniorJPDJ** [comment]
Having this would be amazing!

**Comment by JuniorJPDJ** [comment]
This also adds an ability to select nodePath by helm which is the functionality I need now ;)

**Comment by derekbit** [comment]
@vsellier 
Can you help resolve the conflicts? Thank you.

**Comment by vsellier** [comment]
Hi,

If I'm not wrong, it seems the same  functionnality was already implemented and is available since the v0.0.27 (cf 1f742322165504ad304c8388f970c3f5a32994d9 and 90f926957798d96771945fb266af09e8d477b988), so, I guess this MR can be closed.

Feel free to reopen it if I'm wrong.

**Pull request closed without merging**
