### PR TITLE
Add support for custom path patterns

### PR DESCRIPTION
**Pull request by AlbanBedel**
This PR implement support for configuring the name of the created volume directories using a template as requested in #302.

### CODE REVIEW

**Comment by rpenziol** [comment]
Thanks for implementing this! I built your branch and took this for a spin. It worked exactly like how I'd expect. 

Here's a minimal example of a working config. This will create a new directory based on the `directory-name` annotation on the `PersistentVolumeClaim` 

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-test
provisioner: rancher.io/local-path
parameters:
  nodePath: /storage/container-data
  pathPattern: '{{ index .PVC.Annotations "directory-name" }}'
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: test
  name: test-pvc
  annotations:
    directory-name: test-dir-name
spec:
  storageClassName: local-path-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
```

**Comment by vjm** [comment]
any news on this?

**Comment by derekbit** [comment]
@AlbanBedel 
Can you help resolve the conflict and add a test case? Thank you.
I will review it soon and include it in v0.0.27. Thanks.

**Comment by vjm** [comment]
did this build fail due to a CI issue? is this ready to be released?

**Comment by derekbit** [comment]
> did this build fail due to a CI issue? is this ready to be released?

No worries. The failure is due to amd64 ci broken env. It's ready to be released in v0.0.27.

**Review by derekbit — APPROVED** [review]
LGTM.

TODO: add an e2e test for the feature.

**Pull request merged**
