### PR TITLE
Upgrade sig storage lib external provisioner

### LINKED ISSUE #179: Fix manager termination
The manager does not terminate properly but keeps hanging until it gets killed.

Within the cluster this makes Deployment updates take more time and during local development one cannot simply terminate the manager using ctrl+c but must kill it explicitly.

### PR DESCRIPTION
**Pull request by rorosen**
This also requires to update the minimun go version from 1.21 to 1.22., 
as sig-storage-lib-external-provisioner requires at least go 1.22.0.
Additionally, sig-storage-lib-external-provisioner now uses patch
to modify finalizers on PersistentVolumes, meaning that external
provisioners now need permission rules to patch PersistentVolumes.
The permission is already present in [deploy/local-path-storage.yaml](./deploy/local-path-storage.yaml).

https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/releases/tag/v10.0.0
https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/releases/tag/v10.0.1

Steps executed:

- Update to `sig-storage-lib-external-provisioner/v10 v10.0.1`
- `go mod tidy`
- `go mod vendor`

Fixes #179.

### CODE REVIEW

**Comment by rorosen** [comment]
Tests pass locally with `make && make e2e-test`

```
--- PASS: TestPVCTestSuite (227.23s)
    --- PASS: TestPVCTestSuite/TestPodWithCustomPathPatternStorageClasses (41.71s)
    --- PASS: TestPVCTestSuite/TestPodWithHostPathVolume (20.26s)
    --- PASS: TestPVCTestSuite/TestPodWithLocalVolume (13.02s)
    --- PASS: TestPVCTestSuite/TestPodWithLocalVolumeDefault (13.28s)
    --- PASS: TestPVCTestSuite/TestPodWithNodeAffinity (13.02s)
    --- PASS: TestPVCTestSuite/TestPodWithRWOPVolume (12.93s)
    --- PASS: TestPVCTestSuite/TestPodWithSecurityContext (27.10s)
    --- PASS: TestPVCTestSuite/TestPodWithSubpath (40.10s)
PASS
```

**Comment by derekbit** [comment]
> Tests pass locally with `make && make e2e-test`
> 
> ```
> --- PASS: TestPVCTestSuite (227.23s)
>     --- PASS: TestPVCTestSuite/TestPodWithCustomPathPatternStorageClasses (41.71s)
>     --- PASS: TestPVCTestSuite/TestPodWithHostPathVolume (20.26s)
>     --- PASS: TestPVCTestSuite/TestPodWithLocalVolume (13.02s)
>     --- PASS: TestPVCTestSuite/TestPodWithLocalVolumeDefault (13.28s)
>     --- PASS: TestPVCTestSuite/TestPodWithNodeAffinity (13.02s)
>     --- PASS: TestPVCTestSuite/TestPodWithRWOPVolume (12.93s)
>     --- PASS: TestPVCTestSuite/TestPodWithSecurityContext (27.10s)
>     --- PASS: TestPVCTestSuite/TestPodWithSubpath (40.10s)
> PASS
> ```

Thanks @rorosen 
I'm checking why it failed in the ci runner.

**Review by rorosen — COMMENTED** [review]
LGTM

Thanks for cleaning up the commits @derekbit

**Review by derekbit — APPROVED** [review]

**Comment by superherointj** [comment]
Thanks!

**Comment by derekbit** [comment]
Thanks for the contribution @rorosen.

**Pull request merged**
