### PR TITLE
Bugfix: pvs not deleting was: Remove the assumption that a node's name == its hostname

### PR DESCRIPTION
**Pull request by jan-g**
As per https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#built-in-node-labels

[[[
Note:
The value of these labels is cloud provider specific and is not guaranteed to be reliable. For example, the value of kubernetes.io/hostname may be the same as the node name in some environments and a different value in other environments.
]]]

(This is a quick handwave in the direction of #413)

### CODE REVIEW

**Review by RafalKorepta — APPROVED** [review]
LGTM

**Comment by jan-g** [comment]
I'm not a kustomize expert - I think it'd be useful to demonstrate this working both "from scratch" and also with a granfathered-in PV with the legacy hostname affinity requirement on it - could do with a hand there! (Hence the draft status)

**Comment by jan-g** [comment]
This could really do with https://github.com/rancher/local-path-provisioner/pull/416 to close down the raciness of the e2e tests.

**Comment by jan-g** [comment]
Fixed up the new e2e test (it creates a PV that should be cleaned up & waits on the provisioner; therefore we don't want deleteKustomizeDeployment to target it)

**Comment by jan-g** [comment]
Commenting ro remove the stale tag

**Comment by liangjuf** [comment]
Hi @jan-g thanks for the great fix, when can we get this merged to master? @derekbit @RafalKorepta

**Comment by RafalKorepta** [comment]
Hi @liangjuf I'm not maintainer, so I don't have power to merge.

**Comment by jan-g** [comment]
There's this PR and the one next to it that fixes up some issues with occasional e2e test failures (that means this one's tests should work reliably). This'll need rebasing atop the e2e one once that lands.

Maintainers are a little thin on the ground (and derekbit is in a different tz) so I'd ask for a little patience.

**Review by derekbit — APPROVED** [review]
LGTM

**Pull request merged**
